In [2]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [50]:
data = pd.read_excel('players.xlsx')

In [51]:
data.head()

,player,link,age,club,clublink,current value,old value,difference,change data,appearances,...,club_league:,club_price:,club_statistics:,club_trophies:,trophies_in_recent_years:,club_league_rankings:,avg_injuries_per_season,avg_injury_duration,is_injured,last_injury_date
0,Calvin Ramsay,https://www.transfermarkt.com/calvin-ramsay/pr...,20,Liverpool FC,https://www.transfermarkt.com/fc-liverpool/sta...,€4.00m,€5.00m,€-1.00m,21.12.2023,9,...,Premier League,€874.60m,"{'Matches': '20', 'Goals': '43:18', '+/-': '25...","['2x Champions League Winner', ""4x European Ch...","['English Supercup Winner', 'English League Cu...","['5', '2', '3', '1', '2', '4', '4', '8', '6', ...",1.333333,85.500000,0.0,"Dec 22, 2023"
1,Jonathan Panzo,https://www.transfermarkt.com/jonathan-panzo/p...,23,Nottingham Forest,https://www.transfermarkt.com/nottingham-fores...,€1.20m,€2.00m,€-800k,21.12.2023,37,...,Premier League,€389.75m,"{'Matches': '21', 'Goals': '26:38', '+/-': '-1...","[""2x European Champion Clubs' Cup winner"", '1x...",['Promoted to 1st league'],"['16', '4', '17', '7', '9', '17', '21', '16', ...",1.500000,78.000000,0.0,"Oct 31, 2021"
2,Valentín Barco,https://www.transfermarkt.com/valentin-barco/p...,19,Brighton & Hove Albion,https://www.transfermarkt.com/brighton-amp-hov...,€13.00m,€10.00m,€3.00m,19.12.2023,32,...,Premier League,€503.60m,"{'Matches': '20', 'Goals': '38:33', '+/-': '5'...","['1x English Supercup Winner', '2x English 3rd...",['Promoted to 1st league'],"['6', '9', '16', '15', '17', '15', '2', '3', '...",1.000000,7.500000,0.0,"Aug 29, 2023"
3,Trent Alexander-Arnold,https://www.transfermarkt.com/trent-alexander-...,25,Liverpool FC,https://www.transfermarkt.com/fc-liverpool/sta...,€70.00m,€65.00m,€5.00m,19.12.2023,72,...,Premier League,€874.60m,"{'Matches': '20', 'Goals': '43:18', '+/-': '25...","['2x Champions League Winner', ""4x European Ch...","['English Supercup Winner', 'English League Cu...","['5', '2', '3', '1', '2', '4', '4', '8', '6', ...",2.000000,18.416667,1.0,-
4,Gabriel Magalhães,https://www.transfermarkt.com/gabriel-magalhae...,26,Arsenal FC,https://www.transfermarkt.com/fc-arsenal/start...,€60.00m,€55.00m,€5.00m,19.12.2023,77,...,Premier League,€1.12bn,"{'Matches': '21', 'Goals': '42:20', '+/-': '22...","['13x English Champion', '1x Cup Winners Cup W...","['English Supercup Winner', 'English Supercup ...","['2', '5', '8', '8', '5', '6', '5', '2', '3', ...",1.333333,30.500000,0.0,"Aug 25, 2021"

# National Team Preprocessing

In [52]:
selected_columns = ["National Team", "National Status", "National Matches", "National Goals", "National Assists", "National Yellow Cards", "National Red Cards"]
filtered_data = data[selected_columns]

filtered_data

,National Team,National Status,National Matches,National Goals,National Assists,National Yellow Cards,National Red Cards
0,Scotland,0.0,1.0,0.0,0.0,0.0,0.0
1,England,1.0,5.0,0.0,1.0,1.0,0.0
2,Argentina,1.0,2.0,1.0,1.0,0.0,0.0
3,England,2.0,23.0,2.0,5.0,2.0,0.0
4,Brazil,2.0,6.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
1573,Sweden,0.0,2.0,1.0,0.0,0.0,0.0
1574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1575,Algeria,1.0,1.0,1.0,0.0,0.0,0.0
1576,Portugal,2.0,10.0,7.0,2.0,0.0,0.0
1577,France,1.0,3.0,0.0,1.0,0.0,0.0

Есть строки с NaN, тк у некоторых футболистов вообще нет истории вызова в сборную (их не приглашали).
Поэтому NaN меняем на нули и меняем "National Status".

In [53]:
data = data.fillna(0)

data['National Team'].replace({0: 'Not Invited'}, inplace=True)
data.loc[data['National Team'] == 'Not Invited', 'National Status'] = data['National Status'].replace(0, -1)

filtered_data = data[selected_columns]
filtered_data

,National Team,National Status,National Matches,National Goals,National Assists,National Yellow Cards,National Red Cards
0,Scotland,0.0,1.0,0.0,0.0,0.0,0.0
1,England,1.0,5.0,0.0,1.0,1.0,0.0
2,Argentina,1.0,2.0,1.0,1.0,0.0,0.0
3,England,2.0,23.0,2.0,5.0,2.0,0.0
4,Brazil,2.0,6.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
1573,Sweden,0.0,2.0,1.0,0.0,0.0,0.0
1574,Not Invited,-1.0,0.0,0.0,0.0,0.0,0.0
1575,Algeria,1.0,1.0,1.0,0.0,0.0,0.0
1576,Portugal,2.0,10.0,7.0,2.0,0.0,0.0
1577,France,1.0,3.0,0.0,1.0,0.0,0.0

*Update:* National Status

Теперь у нас есть **четыре статуса выступления за национальную сборную**:
- -1: игрок никогда не вызывался в сборную
-  0: футболист не является действующим игроком своей сборной
-  1: игрок выступает за молодежку сборной
-  2: футболист является действующим игроком своей сборной

In [ ]:
# 2: 'Brazil'|'Argentina'|'England'| 'France'| 'Belgium'| 'Netherlands'| 'Italy'| 'Portugal'| 'Spain'|'Croatia'

# 1: 'Uruguay'| 'USA'| 'Morocco'| 'Colombia'| 'Mexico'| 'Germany'| 'Japan'| 'Switzerland'| 'Denmark'| 'Senegal'

In [54]:
# Словарь для соответствия сборных и их рейтинга
team_ranking = {
    'Brazil': 2, 'Argentina': 2, 'England': 2, 'France': 2, 'Belgium': 2, 'Netherlands': 2,
    'Italy': 2, 'Portugal': 2, 'Spain': 2, 'Croatia': 2,
    'Uruguay': 1, 'USA': 1, 'Morocco': 1, 'Colombia': 1, 'Mexico': 1, 'Germany': 1,
    'Japan': 1, 'Switzerland': 1, 'Denmark': 1, 'Senegal': 1
}

data['National Team Ranking'] = data['National Team'].map(team_ranking).fillna(0)

# Размещаем 'National Team Ranking' после 'National Team'
national_team_index = data.columns.get_loc("National Team")
data = data[list(data.columns[:national_team_index + 1]) + ['National Team Ranking'] + list(data.columns[national_team_index + 1:])]

data = data.iloc[:, :-1]
data

,player,link,age,club,clublink,current value,old value,difference,change data,appearances,...,club_league:,club_price:,club_statistics:,club_trophies:,trophies_in_recent_years:,club_league_rankings:,avg_injuries_per_season,avg_injury_duration,is_injured,last_injury_date
0,Calvin Ramsay,https://www.transfermarkt.com/calvin-ramsay/pr...,20,Liverpool FC,https://www.transfermarkt.com/fc-liverpool/sta...,€4.00m,€5.00m,€-1.00m,21.12.2023,9,...,Premier League,€874.60m,"{'Matches': '20', 'Goals': '43:18', '+/-': '25...","['2x Champions League Winner', ""4x European Ch...","['English Supercup Winner', 'English League Cu...","['5', '2', '3', '1', '2', '4', '4', '8', '6', ...",1.333333,85.500000,0.0,"Dec 22, 2023"
1,Jonathan Panzo,https://www.transfermarkt.com/jonathan-panzo/p...,23,Nottingham Forest,https://www.transfermarkt.com/nottingham-fores...,€1.20m,€2.00m,€-800k,21.12.2023,37,...,Premier League,€389.75m,"{'Matches': '21', 'Goals': '26:38', '+/-': '-1...","[""2x European Champion Clubs' Cup winner"", '1x...",['Promoted to 1st league'],"['16', '4', '17', '7', '9', '17', '21', '16', ...",1.500000,78.000000,0.0,"Oct 31, 2021"
2,Valentín Barco,https://www.transfermarkt.com/valentin-barco/p...,19,Brighton & Hove Albion,https://www.transfermarkt.com/brighton-amp-hov...,€13.00m,€10.00m,€3.00m,19.12.2023,32,...,Premier League,€503.60m,"{'Matches': '20', 'Goals': '38:33', '+/-': '5'...","['1x English Supercup Winner', '2x English 3rd...",['Promoted to 1st league'],"['6', '9', '16', '15', '17', '15', '2', '3', '...",1.000000,7.500000,0.0,"Aug 29, 2023"
3,Trent Alexander-Arnold,https://www.transfermarkt.com/trent-alexander-...,25,Liverpool FC,https://www.transfermarkt.com/fc-liverpool/sta...,€70.00m,€65.00m,€5.00m,19.12.2023,72,...,Premier League,€874.60m,"{'Matches': '20', 'Goals': '43:18', '+/-': '25...","['2x Champions League Winner', ""4x European Ch...","['English Supercup Winner', 'English League Cu...","['5', '2', '3', '1', '2', '4', '4', '8', '6', ...",2.000000,18.416667,1.0,-
4,Gabriel Magalhães,https://www.transfermarkt.com/gabriel-magalhae...,26,Arsenal FC,https://www.transfermarkt.com/fc-arsenal/start...,€60.00m,€55.00m,€5.00m,19.12.2023,77,...,Premier League,€1.12bn,"{'Matches': '21', 'Goals': '42:20', '+/-': '22...","['13x English Champion', '1x Cup Winners Cup W...","['English Supercup Winner', 'English Supercup ...","['2', '5', '8', '8', '5', '6', '5', '2', '3', ...",1.333333,30.500000,0.0,"Aug 25, 2021"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1573,Joel Asoro,https://www.transfermarkt.com/joel-asoro/profi...,24,FC Metz,https://www.transfermarkt.com/fc-metz/startsei...,€1.50m,€2.00m,€-500k,27.06.2023,53,...,Ligue 1,€45.60m,"{'Matches': '18', 'Goals': '16:28', '+/-': '-1...","['2x French Cup winner ', '1x French league cu...","['Promoted to 1st league', 'Relegated from 1st...","['2', '19', '10', '15', '1', '20', '14', '3', ...",0.000000,0.000000,0.0,0
1574,Abdoul Kader Bamba,https://www.transfermarkt.com/abdoul-kader-bam...,29,FC Nantes,https://www.transfermarkt.com/fc-nantes/starts...,€900k,€1.00m,€-100k,16.06.2023,37,...,Ligue 1,€106.55m,"{'Matches': '18', 'Goals': '20:30', '+/-': '-1...","['8x French Champion', '4x French Cup winner '...","['French Cup runner-up', 'French Cup winner ']","['16', '9', '18', '13', '12', '9', '7', '14', ...",1.500000,22.000000,0.0,"Apr 20, 2023"
1575,Yanis Guermouche,https://www.transfermarkt.com/yanis-guermouche...,22,Montpellier HSC,https://www.transfermarkt.com/montpellier-hsc/...,€150k,€200k,€-50k,27.06.2023,23,...,Ligue 1,€101.65m,"{'Matches': '18', 'Goals': '19:23', '+/-': '-4...","['1x French Champion', '2x French Cup winner ']",[],"['12', '13', '8', '8', '6', '10', '15', '12', ...",0.000000,0.000000,0.0,0
1576,Gonçalo Ramos,https://www.transfermarkt.com/goncalo-ramos/pr...,22,Paris Saint-Germain,https://www.transfermarkt.com/fc-paris-saint-g...,€50.00m,€40.00m,€10.00m,16.06.2023,66,...,Ligue 1,€1.05bn,"{'Matches': '18', 'Goals': '44:14', '+/-': '30...","['11x French Champion', '1x Cup Winners Cup Wi...","['French Supercup Winner', 'French Champion', ...","['1', '1', '2', '1', '1', '1', '2', '1', '1', ...",2.000000,8.750000,0.0,"Feb 7, 2023"
1577,Antoine Joujou,https://www.transfermarkt.com/antoine-joujou/p...,20,Le Havre AC,https://www.transfermarkt.com/ac-le-havre/star...,€800k,€500k,€300k,16.06.2023,35,...,Ligue 1,€60.75m,"{'Matches': '18', 'Goals': '19:20', '+/-': '-1...","['1x French Cup winner ', '6x French 2nd tier ...","['Promoted to 1st league', 'French 2nd tier ch...","['1', '8', '12', '6', '7', '4', '8', '4', '7',...",1.000000,54.000000,0.0,"Oct 28, 2023"

In [56]:
data.to_excel('../Football Term Project/players_update.xlsx')

<ipython-input-56-772fa31a8ee5>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  data.to_excel('../Football Term Project/players_update.xlsx')

# Trophies Preprocessing

In [74]:
data = pd.read_excel('df2.xlsx')

In [74]:
data['trophies_in_recent_years']

In [ ]:
import ast

all_trophies = []
for i in range(0, 2547):
    trophy_list_str = data['trophies_in_recent_years'][i]
    if isinstance(trophy_list_str, str):
        trophy_list = ast.literal_eval(trophy_list_str)
        all_trophies += trophy_list

In [ ]:
competition_weights = {
    'Champions League Winner': 10,
    'FIFA Club World Cup winner': 10,
    'Europa League Winner': 9,
    'UEFA Supercup Winner': 8,
    'Champions League runner-up': 8,
    'Europa League runner-up': 7,
    'UEFA Super Cup runner-up': 6,
    'Conference League winner': 6,
    'Conference League runner up': 5,
    'Champions League Participant': 4,
    'Europa League Participant': 3,
    'English Champion': 9,
    'German Champion': 9,
    'Spanish Champion': 9,
    'Italian Champion': 9,
    'French Champion': 9,
    'FA Cup Winner': 8,
    'German Cup winner': 8,
    'Spanish Cup winner': 8,
    'English Supercup Winner': 7,
    'French Supercup Winner': 7,
    'Italian Super Cup winner': 7,
    'English League Cup winner': 6,
    'French league cup winner': 6,
    'FA Cup Runner up': 5,
    'German Cup runner-up': 5,
    'English League Cup runner-up': 4,
    'French league cup runner-up': 4,
    'German Runner Up': 3,
    'relegated from 1st league': 3,
    'English 2nd tier champion': 7,
    'German 2. Bundesliga Champion': 7,
    'Spanish 2nd tier champion': 7,
    'Italian Serie B champion': 7,
    'French 2nd tier champion': 7,
    'Promoted to 1st league': 6,
    'English 3rd tier champion': 5,
    'Promoted to 2. Liga': 5,
    'German 3. Liga Champion': 5,
    'Promoted to third tier': 4,
    'Promotion to 4th division': 3,
    'relegated from 2nd league': 3,
    'relegated from 3rd league': 3,
    'Relegation from 4th division': 2,
    'German Regionalliga Bavaria Champion': 4,
    'German Regionalliga West Champion': 4,
    'Italians U19s Cup Winner': 4,
    'U21 Premier League Sieger': 4,
    'Landespokal Württemberg Winner': 3,
    'Italian Lega Pro Champion (A/C)': 3,
    'Scudetto Serie D': 3,
    'Italienischer Pokalsieger (Serie C)': 3,
    'Herbstmeister (Autumn Champion)': 2,
    'Copa Catalunya Winner': 1
}

## trophies_in_recent_years

In [75]:
import ast
import re

def calculate_player_score(trophies_string, competition_weights):
    try:
        trophies_list = ast.literal_eval(trophies_string)
    except (ValueError, SyntaxError):
        trophies_list = []
    
    scores = [] 
    for trophy in trophies_list:
        match = re.match(r'(\d+)x\s(.+)', trophy)
        if match:
            count = int(match.group(1))
            trophy_name = match.group(2)
            score = competition_weights.get(trophy_name, 0) * count
        else:
            score = competition_weights.get(trophy, 0)
        
        scores.append(score) 
    
    total_score = sum(scores)
    average_score = total_score / len(scores) if scores else 0  
    max_score = max(scores) if scores else 0  
    min_score = min(scores) if scores else 0  
    
    return total_score, average_score, max_score, min_score

In [76]:
results = data['trophies_in_recent_years'].apply(lambda x: calculate_player_score(x, competition_weights))
data[['trophies_total_score', 'trophies_average_score', 'trophies_max_score', 'trophies_min_score']] = pd.DataFrame(results.tolist(), index=data.index)

data.drop(columns=['trophies_in_recent_years'], inplace=True)
data

,Unnamed: 0,full_name,place_of_birth,height,citizenship,position,Foot,player_agent,current_club,joined,...,club_statistics_goals,club_statistics_own_goals,club_statistics_pts,club_league_top_rank,club_league_lowest_rank,club_league_mean_rank,trophies_total_score,trophies_average_score,trophies_max_score,trophies_min_score
0,0,Ederson Santana de Moraes,Osasco (SP),1.88,Brazil Portugal,Goalkeeper,left,Gestifute,Manchester City,79.0,...,58.0,26.0,56.0,1.0,4.0,1.7,184,6.814815,10,4
1,1,Scott Paul Carson,Whitehaven,1.88,England,Goalkeeper,right,Wasserman,Manchester City,31.0,...,58.0,26.0,56.0,1.0,4.0,1.7,184,6.814815,10,4
2,2,Joško Gvardiol,Zagreb,1.85,Croatia,Defender - Centre-Back,left,Marjan Sisic,Manchester City,6.0,...,58.0,26.0,56.0,1.0,4.0,1.7,184,6.814815,10,4
3,3,Nathan Benjamin Aké,Den Haag,1.80,Netherlands Cote d'Ivoire,Defender - Centre-Back,left,Wasserman,Manchester City,42.0,...,58.0,26.0,56.0,1.0,4.0,1.7,184,6.814815,10,4
4,4,Sergio Gómez Martín,Badalona,1.71,Spain,Defender - Left-Back,left,SEG,Manchester City,18.0,...,58.0,26.0,56.0,1.0,4.0,1.7,184,6.814815,10,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2542,2542,Joseph Nduquidi Diazongua Nfingui,Metz,1.87,France Angola,midfield - Central Midfield,NaN,UFC,FC Metz,5.0,...,18.0,35.0,17.0,1.0,20.0,10.4,38,4.222222,7,0
2543,2543,NaN,Bertoua,1.92,Cameroon,Attack - Left Winger,right,Relatives,FC Metz,0.0,...,18.0,35.0,17.0,1.0,20.0,10.4,38,4.222222,7,0
2544,2544,NaN,Saint-Louis,1.82,Senegal,Attack - Left Winger,right,Wasserman,FC Metz,7.0,...,18.0,35.0,17.0,1.0,20.0,10.4,38,4.222222,7,0
2545,2545,Joel Joshoghene Asoro,Haninge,1.76,Sweden Nigeria,Attack - Right Winger,right,BHM Sports Agency,FC Metz,5.0,...,18.0,35.0,17.0,1.0,20.0,10.4,38,4.222222,7,0
2546,2546,გიორგი მიქაუტაძე,Lyon,1.76,Georgia France,Attack - Centre-Forward,right,NaN,FC Metz,1.0,...,18.0,35.0,17.0,1.0,20.0,10.4,38,4.222222,7,0

## club_trophies

In [ ]:
data['club_trophies']

In [ ]:
import ast
import re

all_club_trophies = []
for i in range(0, 2547):
    club_trophy_list_str = data['club_trophies'][i]
    if isinstance(club_trophy_list_str, str):
        club_trophy_list = ast.literal_eval(club_trophy_list_str)
        for trophy in club_trophy_list:
            match = re.search(r'\d+x (.+)', trophy)
            if match:
                trophy_name = match.group(1)
                all_club_trophies.append(trophy_name)
            else:
                all_club_trophies.append(trophy)

set(all_club_trophies)

In [ ]:
club_competition_weights = {
    'FIFA Club World Cup winner': 10,
    'UEFA Champions League Winner': 10,
    'UEFA Europa League Winner': 9,
    'UEFA Supercup Winner': 8,
    'Intercontinental Cup Winner': 8,
    'UEFA Cup Winner': 9,
    'Cup Winners Cup Winner': 8,
    'Inter-Cities Fairs Cup winner': 7,
    'European Champion Clubs’ Cup winner': 10,
    'Intertoto-Cup Winner': 6,
    'Conference League winner': 7,
    'English Champion': 9,
    'German Champion': 9,
    'Spanish Champion': 9,
    'Italian Champion': 9,
    'French Champion': 9,
    'FA Cup Winner': 8,
    'German Cup winner': 8,
    'Spanish Cup winner': 8,
    'Italian Cup winner': 8,
    'French Cup winner': 8,
    'English League Cup winner': 7,
    'French league cup winner': 7,
    'League Cup Winner': 7,
    'English Supercup Winner': 7,
    'German Super Cup Winner': 7,
    'Spanish Super Cup winner': 7,
    'Italian Super Cup winner': 7,
    'French Supercup Winner': 7,
    'English 2nd tier champion': 6,
    'German 2. Bundesliga Champion': 6,
    'Spanish 2nd tier champion': 6,
    'Italian Serie B champion': 6,
    'French 2nd tier champion': 6,
    'English 3rd tier champion': 5,
    'German 3. Liga Champion': 5,
    'English 4th tier champion': 4,
    'Football League Trophy Winner': 3,
    'German U19 Champion': 4,
    'French Youth Cup winner': 4,
    'U21 Premier League Sieger': 4,
    'Landespokal Winners (for all)': 3,
    'Italian Lega Pro Champion (A/B/C)': 3,
    'Italian Lega Pro 2 Champion (B/C/D)': 3,
    'Scudetto Serie D': 3,
    'Mitropacup': 3,
    'Winner Copa RFEF': 2,
    'Winner Coupe Charles Drago': 2,
    'Winner of the German Amateur championship': 2,
    'Copa Catalunya Winner': 2,
    'Copa Eva Duarte Winner': 2,
    'Western German Cup Winner': 2,
}

In [78]:
def calculate_club_score(trophies_string, competition_weights):
    try:
        trophies_list = ast.literal_eval(trophies_string)
    except (ValueError, SyntaxError):
        trophies_list = []
    
    scores = []
    for trophy in trophies_list:
        match = re.match(r'(\d+)x\s(.+)', trophy)
        if match:
            count = int(match.group(1))
            trophy_name = match.group(2)
            if trophy_name in competition_weights:
                
                score = competition_weights[trophy_name] * count
                scores.append(score)  
        else:
            if trophy in competition_weights:
                scores.append(competition_weights[trophy])
    
    if not scores:  
        min_score_from_weights = min(competition_weights.values()) if competition_weights else 0
        
        return [0, 0, 0, min_score_from_weights]
    
    total_score = sum(scores)
    average_score = total_score / len(scores) if scores else 0
    max_score = max(scores) if scores else 0
    
    min_score = min(scores) if scores else min(competition_weights.values())

    return total_score, average_score, max_score, min_score

In [79]:
results = data['club_trophies'].apply(lambda x: calculate_club_score(x, club_competition_weights))

data[['club_trophies_total_score', 'club_trophies_average_score', 'club_trophies_max_score', 'club_trophies_min_score']] = pd.DataFrame(results.tolist(), index=data.index)

data.drop(columns=['club_trophies'], inplace=True)
data

,Unnamed: 0,full_name,place_of_birth,height,citizenship,position,Foot,player_agent,current_club,joined,...,club_league_lowest_rank,club_league_mean_rank,trophies_total_score,trophies_average_score,trophies_max_score,trophies_min_score,club_trophies_total_score,club_trophies_average_score,club_trophies_max_score,club_trophies_min_score
0,0,Ederson Santana de Moraes,Osasco (SP),1.88,Brazil Portugal,Goalkeeper,left,Gestifute,Manchester City,79.0,...,4.0,1.7,184,6.814815,10,4,303,37.875,81,8
1,1,Scott Paul Carson,Whitehaven,1.88,England,Goalkeeper,right,Wasserman,Manchester City,31.0,...,4.0,1.7,184,6.814815,10,4,303,37.875,81,8
2,2,Joško Gvardiol,Zagreb,1.85,Croatia,Defender - Centre-Back,left,Marjan Sisic,Manchester City,6.0,...,4.0,1.7,184,6.814815,10,4,303,37.875,81,8
3,3,Nathan Benjamin Aké,Den Haag,1.80,Netherlands Cote d'Ivoire,Defender - Centre-Back,left,Wasserman,Manchester City,42.0,...,4.0,1.7,184,6.814815,10,4,303,37.875,81,8
4,4,Sergio Gómez Martín,Badalona,1.71,Spain,Defender - Left-Back,left,SEG,Manchester City,18.0,...,4.0,1.7,184,6.814815,10,4,303,37.875,81,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2542,2542,Joseph Nduquidi Diazongua Nfingui,Metz,1.87,France Angola,midfield - Central Midfield,NaN,UFC,FC Metz,5.0,...,20.0,10.4,38,4.222222,7,0,25,12.500,18,7
2543,2543,NaN,Bertoua,1.92,Cameroon,Attack - Left Winger,right,Relatives,FC Metz,0.0,...,20.0,10.4,38,4.222222,7,0,25,12.500,18,7
2544,2544,NaN,Saint-Louis,1.82,Senegal,Attack - Left Winger,right,Wasserman,FC Metz,7.0,...,20.0,10.4,38,4.222222,7,0,25,12.500,18,7
2545,2545,Joel Joshoghene Asoro,Haninge,1.76,Sweden Nigeria,Attack - Right Winger,right,BHM Sports Agency,FC Metz,5.0,...,20.0,10.4,38,4.222222,7,0,25,12.500,18,7
2546,2546,გიორგი მიქაუტაძე,Lyon,1.76,Georgia France,Attack - Centre-Forward,right,NaN,FC Metz,1.0,...,20.0,10.4,38,4.222222,7,0,25,12.500,18,7

In [80]:
data.to_excel('../Football Term Project/df3.2.xlsx')

<ipython-input-80-4f872679184c>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  data.to_excel('../Football Term Project/df3.2.xlsx')